### ISSUE TITLE
ImportError: cannot import name 'DIRS' from 'pymrt'

### ISSUE THREAD

**Issue by tungngovn** [norok2/pymrt#1]
Hi.
When I run this import code `import pymrt.geometry`, an error occur: 

```
Traceback (most recent call last):
  File "generate_batch_data_pairs.py", line 7, in <module>
    import pymrt.geometry
  File "/home/tungngo/anaconda3/envs/tf-gpu-cuda8/lib/python3.7/site-packages/pymrt/geometry.py", line 55, in <module>
    from pymrt import INFO, DIRS
ImportError: cannot import name 'DIRS' from 'pymrt' (/home/tungngo/anaconda3/envs/tf-gpu-cuda8/lib/python3.7/site-packages/pymrt/__init__.py)
```

Could you please show me how to fix this? Thank you.

**Comment by norok2** [comment]
Hi,
What version of PyMRT are you running? That sub- package is long gone from PyMRT. Try pip-installing `raster-geometry` instead.
